name: Build spark-sql-perf JAR

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      # 新增步骤：安装 sbt
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        # with:
        #   sbt-version: '1.9.9' # 可以指定 sbt 版本，默认为最新版

      - name: Build with sbt
        run: sbt package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spark-sql-perf-jar
          path: target/scala-*/spark-sql-perf_*.jar
          if-no-files-found: error
