name: Build and Upload Entire Project Directory

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Build with sbt
        run: sbt package

      # 主要修改点在这里
      - name: Upload entire project directory
        uses: actions/upload-artifact@v4
        with:
          # 修改产物名称以反映其内容
          name: full-project-archive
          # 将路径修改为 ./ 来指定当前目录（整个仓库）
          path: ./
          if-no-files-found: error
